# Path to directory where repositories live
repo_path: /afs/ir/class/cme211/git/repos_hw3/

# Categories to grade, separated by a space
categories: "functionality-65 design-20 style-10 writeup-5"

# Hw to be graded
hw: hw3

# Name of sunets-git-TA map file
map_ta: /afs/ir/class/cme211/git/repos_hw3/TA_assignments.txt

# Git root for creation of figs and data files
root_git: /afs/ir/class/cme211/git/

# Absolute minimum number of files to submit (the main programming files)
min_files: 1
