# Path to directory where repositories will be cloned to
repo_path: /afs/ir/class/cme211/git/repos/

# Categories to grade, separated by a space
categories: "functionality-70 style-10 writeup-20"

# Hw to be graded
hw: hw2

# If true, all the feedback of the repos will be generated, else only local.
global: true

# Name of sunets-git-TA map file
map_ta: /afs/ir/class/cme211/git/repos/TA_assignments.txt

# Git root for creation of figs and data files
root_git: /afs/ir/class/cme211/git/
