# Path to directory where repositories will be cloned 
repo_path: /afs/ir/class/cme211/git/repos/

# Categories to grade, separated by a space
categories: "functionality-40 style-20 design-30 writeup-10"

# Hw to be graded
hw_dir: hw1/

# If true, all the feedback of the repos will be generated, else only local.
global: true

# Name of student-git map file
map_git: /afs/ir/class/cme211/git/repos/SU2Git.yaml