# Feedback file name
file_name: feedback.txt

# Path to directory where repositories will be cloned 
repo_path: /afs/ir/class/cme211/git/repos  

root_path: /afs/ir/class/cme211/git/

# If true, all the feedback of the repos will be generated, else only local.
global: true

# Name of student roster file (one username per line)
roster: utilities/git-utils/students.txt